### ISSUE TITLE
`rzpipe` test always fails on a system without `rizin` binary

### ISSUE THREAD

**Issue by trofi** [rizinorg/rizin#1192]
Observed as a test failure as part of testsuite run on Gentoo distribution:

```
>>> Test phase: dev-util/rizin-0.2.1
meson test -C /tmp/portage/dev-util/rizin-0.2.1/work/rizin-0.2.1-build --num-processes 16
ninja: Entering directory `/tmp/portage/dev-util/rizin-0.2.1/work/rizin-0.2.1-build'
...
57/78 rzpipe                       FAIL            0.04s   exit status 1
>>> MALLOC_PERTURB_=23 /tmp/portage/dev-util/rizin-0.2.1/work/rizin-0.2.1-build/test/unit/test_rzpipe
...
```

This seems to happen because test assumes that `rizin` binary is available in $PATH. It is not when test is ran on a fresh system:

rizin-v0.2.1/test/unit/test_rzpipe.c:

```c
static bool test_rzpipe(void) {
#ifndef __WINDOWS__
        RzPipe *r = rzpipe_open("rizin -q0 -"); // <<<--- HERE
        mu_assert("rzpipe can spawn", r);
        char *hello = rzpipe_cmd(r, "?e hello world");
        mu_assert_streq(hello, "hello world\n", "rzpipe hello world");
        free(hello);
        rzpipe_close(r);
#else
        mu_test_status = MU_TEST_BROKEN;
#endif
        mu_end;
}
```

**Comment by ret2libc** [comment]
The only solution I could think of is to have a new header file in `test/unit/test_config.h.in` with a `#define RIZIN_BUILD_PATH @RIZIN_BUILD_PATH@` with the final header file generated from `test/unit/meson.build` like what is done for rz_version.h.

Then we can use include the header in test_rzpipe.c and use `RIZIN_BUILD_PATH` instead of just "rizin".

@trofi are you already familiar with meson by any chance? Are you interested in contributing and trying to patch this?

**Comment by trofi** [comment]
I know almost nothing about meson :) Specifically I'm not sure how to handle include directories for generated headers. Tried with ` include_directories: [..., '.'],`

Here is my attempt: https://github.com/rizinorg/rizin/pull/1198
