### ISSUE TITLE
Extract SPP into subproject

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1388]
Currently it's located in `shlr/spp` and just a copy. I suggest to move it to subprojects for now.

**Comment by XVilka** [comment]
There is also fle `shlr/spp/rz_api.c` which is completely unnecessary since it can use the same functions directly from `RzUtil`.

**Comment by ret2libc** [comment]
Yes, but consider `spp` is a separate (and possibly standalone) project.

**Comment by ret2libc** [comment]
After looking at it it's probably much better to move spp into librz instead of treating it as a standalone project. It's much easier to write spp code if it always depends on rz_util..

Right now it would be almost impossible to move spp into a subproject because it needs rz_util which is defined by this repository. So there is a chicken and egg issue.

Closing this.
