### ISSUE TITLE
project saved in 0.2.1, opened with 0.3.0-git, base types cannot be found

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1497]
Still for me to investigate more.

Quickly, what i did was creating a project in 0.2.1, then load with current dev and saving the project again. When saving it was saying that some of the base types could not be found. I saved anyway. When re-opening the project, there were multiple errors of parsing like:

```
error parsing "mbsinit" func arg type "(null)*": Wrongly formed ............
Cannot parse type_descriptor's type field
```

**Comment by XVilka** [comment]
As I explained before on the "Types" channel it cannot be done in principle. Before, the TinyCC code was using for parsing C descriptions from `td` and `to` commands and convert them to the SDB key-value format where every parsed type was saved as string. While using TCC made sure the syntax is correct, the pre-shipped "standard" types from `librz/analysis/d/` were in the text form of SDB and had many mistakes. For example, there was unused `foo.PTRTO=bla` which probably meant `typedef bla *foo` but never actually used. Some types didn't make sense - e.g. function arguments that were function pointers were simply marked as `func` which is incorrect C as well. Moreover, the database was riddled with mistakes, unnamed arguments, inconsistencies. This is because SDB was never validated upon loading and was accessed on-demand since it was used as the main storage of the type information. With my refactoring the loading is done only once, when `asm.arch`, `asm.bits`, `asm.os`, etc are changed or upon binary loading. During this process we parse all of SDB keys, parse corresponding types and verify their consistency. The saved project from before my commit had all these errors, inconsistencies serialized. We simply cannot convert them automatically.

**Comment by ret2libc** [comment]
Thanks for the explanation, makes sense! I'll just double check as i have time, but i think it was just that, yes!

**Comment by ret2libc** [comment]
@XVilka I think it's worth looking quickly at this. What I did was essentially:
1. open a file with 0.2.0 and saving a project
2. open the project with current version . you get some warnings.
3. save again the project with current version (other few warnings, but that's fine i guess)
4. open the project with current version. I would not expect to find again errors now, because the project should be fully migrated to current version, however i now get tons of errors on loading


This seems to be caused by things like:
```
func.mbsinit.arg.0=(null)*,ps
func.mbsinit.args=0x1
func.mbsinit.ret=int
```

in the project file. Can we have `void *` or something else that makes sense when the type cannot be correctly stored? I think it is alright to have a generic type (even uint64_t or uint32_t).

**Comment by ret2libc** [comment]
Given it's just about project migrations and we are still in 0.x, you can also choose to close this and ignore the problem if you think it's too much trouble for little benefit at this point.

**Comment by XVilka** [comment]
Will check once more stuff for 0.3.0 addressed.

**Comment by XVilka** [comment]
I will add `unknown_t` type, like in Ghidra.
