### ISSUE TITLE
Add higher order functions in rizin shell

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#152]
As an extension of the classical iterators (see [Rizin Book - Loops](https://book.rizin.re/scripting/loops.html)) it might be interesting to add these higher kinded constructs in rizin scripting language:

- map
- fold
- filter

Since rizin is quite close to the shell, see the [example of them in ZSH](http://yannesposito.com/Scratch/en/blog/Higher-order-function-in-zsh/):
```sh
$ filterl 'echo $1|grep a >/dev/null' ab cd ef ada
ab
ada

$ folda '$1+$2' {1..5}
15

$ folda '$1*$2' {1..20}
2432902008176640000

$ mapl 'echo X $1:t Y' ~/.zsh/functional/src/*
X each Y
X filter Y
X fold Y
X map Y

$ mapa '$1*2' {1..3}
2
4
6

$ mapl 'echo result $1' $(mapa '$1+5' $(mapa '$1*2' {1..3}))
result 7
result 9
result 11
```

We can introduce even JSON-focused `mapj`, `foldj`, `filterj`, that operate on the JSON output instead

cc @thestr4ng3r

**Comment by ret2libc** [comment]
As I explained on Mattermost, I'm not a big fan of this. I would like to see:
1) a real syntax for rizin
2) a real use case for rizin, which not only does simple math operation but actually works with the data

Moreover, I think this is very low priority right now as we don't *have to* make rizin shell yet another language, as there are many others for that. Indeed, as said by @thestr4ng3r , it would be much better to make sure interactions with other languages (e.g. python) works well and that you can easily switch between rizin shell and python. Those things can be easily done with any programming language.

What are the advantages of implementing such things directly in rizin?
I see some disadvantages:
1) development complexity and maintenance
2) having to learn yet another language just for doing some things. People already find the basic rizin commands hard to remember and understand and adding such a feature is imho too much

**Comment by ret2libc** [comment]
I propose to close this for now. I don't see this happening or being useful for the next 3 years at least. None will ever learn such features, considering that very few people even know the full rizin/r2 syntax or even the basic set like `~` and other things. Let's use python/perl or whatever else for doing complicated operations with the rizin data. I see this just as showing off something, but not really useful at the end. Re-open if you feel otherwise, but before doing so please provide things asked in previous comment.
