### ISSUE TITLE
macOS homebrew support

### ISSUE THREAD

**Issue by kciredor** [rizinorg/rizin#160]
Having (mostly) everything scripted when (re-)provisioning my laptop, it would be nice for rizin to be added to homebrew like radare2 https://github.com/Homebrew/homebrew-core/blob/master/Formula/radare2.rb.

That way it's easy to just add another brew install and it'll be updated upon every brew update.

**Comment by XVilka** [comment]
It makes sense to do after the first release is out.

**Comment by ret2libc** [comment]
Hi @kciredor ! Would you be available to help us with that? It should be similar to radare2, but using `meson`/`ninja` instead of `configure`/`make` for build/install steps.

**Comment by Maijin** [comment]
Some docs - https://github.com/toolmantim/tap-release

**Comment by XVilka** [comment]
A heads up for the maintainers - we [tagged the first release](https://github.com/rizinorg/rizin/releases/tag/0.1.0), building artifacts and writing the release notes. If you planned to craft a new tap - it's a good time to do so.

**Comment by ret2libc** [comment]
Hi @kciredor . I'm planning to work relatively soon on providing repositories for linux distros so that they can remain updated with Rizin versions without having to re-download the release every time. It will also help us at least until distros will start packaging Rizin.

However, many of us are not working on Mac (not usually at least) so it would be great to receive some help on that. Are you still interested in the homebrew part? Would you be available to help with a basic formula and maybe look at what we need to do/setup to use https://github.com/toolmantim/tap-release ? It would be great to setup something like that, because that way we can just automatically update the formula when we release a new update, without requiring manual intervention.

Let us know please. Thanks.

**Comment by pcolladosoto** [comment]
Hi all! According to the current [`INSTALL.md`](https://github.com/rizinorg/rizin/blob/fc24887c5cabe649cd22bf681c9280666d4f883e/INSTALL.md) I believe there's no macOS Homebrew tap available for Rizin.

I usually work on a macOS machine and I would be more than happy to lend a hand and get that tap up and running.

Before doing so I would really appreciate it if you could tell me wether this is something you'd like: I'd hate to just bog you down with something you're not really seeking...

Thanks a ton for Rizin 😸

**Comment by ret2libc** [comment]
I'm not sure it's still worth it after all TBH... Rizin is already in homebrew core formulas and it is updated right now so maybe we can just rely on that. What do you think?

**Comment by pcolladosoto** [comment]
As soon as I read the [`INSTALL.md`](https://github.com/rizinorg/rizin/blob/fc24887c5cabe649cd22bf681c9280666d4f883e/INSTALL.md?plain=1#L38-L40) I just didn't think about trying to install Rizin: I assumed it wasn't available at all.

Maybe we can update that line so that other users just use `brew` to install it?

Sorry for the noise... 😅

**Comment by ret2libc** [comment]
Definitely! I think there was no rizin formula at the time. Do you want to update the doc by sending a PR by any chance? 😀

**Comment by pcolladosoto** [comment]
On it 😼
