### ISSUE TITLE
Create special category for "system" commands

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1840]
Currently there are commands like
- `uname`
- `uniq`
- `clear`
- ...

I wonder if it makes sense to group them together and put in a separate YAML file, their handlers in a separate C file. They don't really belong with the rest.

**Comment by ret2libc** [comment]
What would be the name of the group?

**Comment by XVilka** [comment]
`shell` maybe?

**Comment by DMaroo** [comment]
I think this should be done before #1854 is merged. This is because there are at least 4 shell commands starting with `c` (`cd`, `cat`, `cp`, `clear` (or `cls`)). It would be nicer to port them before, rather than re-porting them once #1854 gets merged.

**Comment by ret2libc** [comment]
> I think this should be done before #1854 is merged. This is because there are at least 4 shell commands starting with `c` (`cd`, `cat`, `cp`, `clear` (or `cls`)). It would be nicer to port them before, rather than re-porting them once #1854 gets merged.

Please note that once things are ported to rzshell it is very easy to move one command from one place to the other, because it is just a matter of moving the entry in the .yaml file and everything will still work easily. So if you want to work on this first, sure, but in theory it should not be too much work even if done after.
