### ISSUE TITLE
Add rz-ghidra to docker container

### ISSUE THREAD

**Issue by ogre2007** [rizinorg/rizin#1903]
**Is your feature request related to a problem? Please describe.**
I cannot install rz-ghidra in rizin docker container. It requires compilation, but after build stage there is no cmake etc.

**Describe the solution you'd like**
Add possibility to build docker container with implicit rz-ghidra.

**Describe alternatives you've considered**
Add possibility to install rz-ghidra without compilation.

**Comment by ret2libc** [comment]
Ok this is my fault, see 86ba9550c70c6362cd2f25d73d5216ff54e451ac and https://github.com/rizinorg/rizin/pull/1381 .
As commented in the commit description, we should allow rz-pm to install things in a specific directory, so that the build of rz-ghidra can be done in the stage0 container with DESTDIR=/tmp/rizin-install and then the binary files moved into the stage1 container. I hope to move forward rz-pm status before the next release.

**Comment by ogre2007** [comment]
> Ok this is my fault, see [86ba955](https://github.com/rizinorg/rizin/commit/86ba9550c70c6362cd2f25d73d5216ff54e451ac) and #1381 . As commented in the commit description, we should allow rz-pm to install things in a specific directory, so that the build of rz-ghidra can be done in the stage0 container with DESTDIR=/tmp/rizin-install and then the binary files moved into the stage1 container. I hope to move forward rz-pm status before the next release.

As a workaround, I've used this:
```
FROM rizin/rizin:latest

USER root

RUN apt install -y cmake gcc g++ pkg-config && rz-pm -i rz-ghidra

USER rizin

CMD ["/bin/bash"]
```
So it may be useful for someone. But the resulting image size raised from 400 MB to 1.8 GB, so it's not a cure.

**Comment by ret2libc** [comment]
Thanks a lot. Yes that's was what I had in mind for people who wanted rz-ghidra right now. As you said, it increases a lot the size because of all the building files and the build requirements (e.g. g++, etc.).

Ideally, we should be able to tell rz-pm to install rz-ghidra in a particular DESTDIR and then, using staged Dockerfile, we can just move the binary files in the DESTDIR into the final container, which would contain only the final necessary files instead of all the build dependencies and source code.
