### ISSUE TITLE
Disassembly Colors are broken with latest rizin dev

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rizin#2864]
With rizin from submodule (b79201b49a0d687c854b6e2f0c88fc8a7f2afa61): 
![Bildschirmfoto 2022-08-01 um 17 58 21](https://user-images.githubusercontent.com/1460997/182190472-124afd53-645c-428e-82de-8b03b2c57424.png)

With rizin dev (fc24887c5cabe649cd22bf681c9280666d4f883e):
![Bildschirmfoto 2022-08-01 um 17 58 09](https://user-images.githubusercontent.com/1460997/182190711-39fd1845-ac0f-4fe8-b1f0-f26b9b28254c.png)

Notice how many of the colors do not work and are just blue.
I suspect this to be related to https://github.com/rizinorg/rizin/pull/2417 and #2996 somehow.

**Comment by b1llow** [comment]
Looks like a bug of `rz_cons_html_filter`

**Comment by Rot127** [comment]
> Looks like a bug of rz_cons_html_filter

Agree on that.
This issue could also be related to https://github.com/rizinorg/cutter/issues/2945

**Comment by Rot127** [comment]
I don't really grasp the parsing algorithm yet and can't look into it more today. But the problem seems to be that `rz_cons_html_filter` does not insert `</font><font ...>` into the resulting string, if one escape sequence follows directly another.

E.g.:
`.. \033[0m\033[38;2;230;225;207msp ..."` (note how after the reset `\033[0m` follows directly the color `\033[38;2;230;225;207m`.

When working on https://github.com/rizinorg/rizin/pull/2417 I was wondering why the old algorithm added a space after each reset escape string. Now I know why :D

But as a general ideas.
1. We could also not use `rz_cons_html_filter` and add another token color like `rz_print_colorize_asm_str`. But it colors the code with in HTML.
2. Or add a `html_colors` flag argument to `rz_print_colorize_asm_str` so it translates the pallette colors to the html ones.

**Comment by thestr4ng3r** [comment]
Good findings! I think `rz_cons_html_filter()` should be fixed nonetheless, unless we want to remove it entirely (which might be possible by directly converting from ansi escape codes to Qt structures, but I still find the html somewhat useful).
I would not add anything to `rz_print_colorize_asm_str()` or make a variant of it, also because there is more code emitting ansi colored text in the disassembly process and ansi is generally a good base representation imo.
