### ISSUE TITLE
Fix `pCd` missing instructions problems

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3318]
![image](https://user-images.githubusercontent.com/562321/213987054-f22e6d2c-09f3-453a-a57e-bdd337b48d38.png)

The problem is that the second columns starts at 0x100003a64, but the first one ends with 0x100003a5c. So there is an instruction (0x100003a60) that is not displayed.

However... this is not strictly a problem with your conversion, so if you want go ahead but let's create an issue for this at least.

_Originally posted by @ret2libc in https://github.com/rizinorg/rizin/issues/3213#issuecomment-1399918455_

See `librz/core/cmd/cmd_print.c`

**Comment by UbhayAnand1** [comment]
hello @XVilka, I have been reviewing the main files and the "good first issues" that you have identified. While I kindof understand the solutions provided by other members, I am finding it difficult to fully grasp the complexity of these issues and how to recreate them. Could you provide guidance on how I should approach these issues in order to gain a better understanding? Your assistance would be greatly appreciated.
