### ISSUE TITLE
Rizin should have the concept of Global Variables

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/rizin#333]
**Is your feature request related to a problem? Please describe.**
Currently, Rizin does not have the concept of Global Variables, this means that one can't set an address as a global variable.
Not only that, but Rizin also doesn't detect global variables and label them automatically upon analysis. Thus, you can see addresses referenced in the disassembly, while they are clearly globals.

The current workaround that the user can do is to assign a flag in an address of a global variable. In addition, users can also apply structs to these addresses.

Worth to mention, this is highly important for decompilers that rely on global variables and their types.

**Describe the solution you'd like**
1. Let users the option to define a global variable and its type
2. Automatically detect and define global variables and their type upon analysis

**Comment by ret2libc** [comment]
> 1. Let users the option to define a global variable and its type

One one side it would be cool to have a command like `afvg` to define `global variables`, on the other side `afv` means `analysis function variables` and globals are not really part of any function.

**Comment by karliss** [comment]
Considering potential approaches does rizin need a new separate mechanism for it or just use the information which is already there and maybe add some commands for more easily managing it. Is there any additional information beside name, offset and type that needs to be stored? There is already a bit of mess due to having multiple mechanisms for naming functions. Having two different mechanisms for defining type at address would also be confusing.

Parts that could use global variable type information:
* Automatic assignment from debug symbols
* type analysis
    * propagating types obtained from accessing global variable fields
    * defining new global variables with correct type when a global variable has pointer field pointing to other structure
    * variable type deduction from function argument types
* recognizing field access in disassembly
* type synchronization with decompiler

**Comment by XVilka** [comment]
Was fixed and supported in both Rizin and Cutter.
