### ISSUE TITLE
Function argument and return types should be inferred from DWARF

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3470]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | FreeRTOS ARMv7 (Cortex-M
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARMv7
| `rizin -v` full output, **not truncated** (mandatory)  |  https://github.com/rizinorg/rizin/commit/7670834a9cb74aa9c0f34f44cc5a3c19fffe29d8

### Actual behavior

<img width="1106" alt="Screenshot 2023-04-19 at 15 39 02" src="https://user-images.githubusercontent.com/203261/233003562-b390cf28-2443-4c13-9846-9a047f66527a.png">

Note, that it loaded the `void VListInsertEnd( List_t * const pxList, ListItem_t * const pxNewListItem )` from the DWARF, but didn't apply the types of arguments to the function signature.

This function is common in FreeRTOS and should be presented in any ARM target: https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/aa987a3443b60894bc64714135bca44831406886/list.c#L98

**Comment by b1llow** [comment]
Could you provide me with this binary file?

**Comment by XVilka** [comment]
@imbillow I compiled some artificial example with different types used for ARMv7 (Alpine Linux, GCC 11 + musl) and Tricore (Hightec), with and without debug information. It will be helpful for the Tricore analysis as well. See attached files (with sources):
[float_ex1.zip](https://github.com/rizinorg/rizin/files/11411148/float_ex1.zip) (an extended version of test from https://github.com/rizinorg/rizin/issues/3282):
```
./float_ex1_arm
a = 5.400000 b = 0.000008 c = 5.400035e+00
Some.a = 5 Some.b = blabl Some.c = 5.400035
```
See `new_some()` and `fn1()` functions in particular in all these samples.

If you need more examples, you could use Alpine 3.16 ARMv7 VM that can be created and started using these scripts (for mounting shared directory in the guest, use `mount -t 9p -o trans=virtio test_mount /mnt`): 
[alpine_armv7_script.zip](https://github.com/rizinorg/rizin/files/11411211/alpine_armv7_script.zip)

Feel free to create tests based on these files, if you think they are suitable.

**Comment by b1llow** [comment]
After some observation and debugging, I've found the following issue.

The ARMv7 ELF file uses the ARM16 call convention. As per the ARMv7 calling convention, the first four arguments are passed through registers R0-R3, and any additional arguments are passed on the stack. However, by observing the DWARF information, I found that all subprograms (functions) have a formal_parameter with a location attribute of fbreg - xxx, which indicates they are stored on the stack.

So, why is there this bug?

During `rz_core_analysis_everything` process, but before `rz_analysis_dwarf_integrate_functions`, Rizin has already created all the variables for the function, based on auto-naming and the standard ARM16 calling convention. But during `rz_analysis_dwarf_integrate_functions`, it adds new variables based on DWARF. Theoretically, since the location of the DWARF-based variables is the same as the standard calling convention location, the previously created variables should be removed during the `rz_analysis_var_resolve_overlaps` process. However, due to the location attribute in the DWARF information being fbreg - xxx, there are no overlaps in positions. As a result, we have roughly twice the number of formal_parameter and variable instances.

**Comment by XVilka** [comment]
For the reference:
> 2.5.1.2 Register Based Addressing
>
> The following operations push a value onto the stack that is the result of adding the contents of a register to a given signed offset.

> DW_OP_fbreg
> The DW_OP_fbreg operation provides a signed LEB128 offset from the address specified by the location description in the DW_AT_frame_base attribute of the current function. (This is typically a “stack pointer” register plus or minus some offset. On more sophisticated systems it might be a location list that adjusts the offset according to changes in the stack pointer as the PC changes.)

From https://dwarfstd.org/dwarf4std.html

See also:
- https://lists.linuxfoundation.org/pipermail/dwarf-discuss/2005-April/000092.html
- https://blog.tartanllama.xyz/writing-a-linux-debugger-variables/
- https://github.com/NationalSecurityAgency/ghidra/issues/2322#issuecomment-702898909
