### ISSUE TITLE
Broken test `typedef self-reference`

### ISSUE THREAD

**Issue by b1llow** [rizinorg/rizin#3700]
Borken and it should not depend on the DWARF information.

```
NAME=typedef self-reference
BROKEN=1
FILE=bins/elf/analysis/self-ref-typedef
CMDS=<<EOF
tt const_reference
ttc const_reference
t const_reference
tc const_reference
EOF
EXPECT=<<EOF
pf d a
struct const_reference {
	int a;
};
EOF
RUN
```

Check after https://github.com/rizinorg/rizin/pull/3703 is merged

**Comment by XVilka** [comment]
@imbillow it seems the problem not in the self-reference per se, but because new code doesn't create "dangling" typedef, without struct defined first. Is it possible to change the DWARF code to allow this? It caused more issues than I initially thought. The pattern of defining typedef first, then structure turned out to be common.
