### ISSUE TITLE
Highlighting function names that look like decimal or hexadecimal numbers

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#4072]
Currently, if you call a function with a name like `fcn.bla.foo_Goo7_ADC_sdf_aaa_dfg_FFF_7823_ggf_0x70_` some parts of the function name in the call instruction (e.g. `bl` for ARM64) would be highlighted as numbers - `ADC`, `aaa`, `FFF`, `7823`, `0x70`.

Obviously this is wrong and function name should have uniform color.

<img width="1112" alt="Screenshot 2024-01-05 at 8 05 06 PM" src="https://github.com/rizinorg/rizin/assets/203261/518da9b1-4e5f-4618-abb7-6940d73e3db3">

**Comment by giridharprasath** [comment]
Hey @XVilka , I am new to rizin and I was looking into this issue, seems like the caller function which tokenizes the asm str is marked for deprecation https://github.com/rizinorg/rizin/blob/9ed0496e54752db228063f9a4c8876bd40c8fc6e/librz/asm/asm.c#L1749

Every token after a separator could be mistaken as a mnemonic too :
![ScreenShot_2024-01-08_at_03:00:57-AM](https://github.com/rizinorg/rizin/assets/17312540/abaddc4f-3059-4ab9-a9b2-e59b19cbfea2)

Should we replace with `get_token_patterns` from `asm_bf.c` ?

**Comment by Rot127** [comment]
Implementing the [tokenization](https://github.com/rizinorg/rizin/blob/dev/doc/asm_strings.md) for `AArch64`  would be indeed nice. Though I'm not sure if it fixes this issue. The symbol name (`fcn.bla....`) should be replaced _after_ the asm string was tokenized.

Better check first, how this happens. I think the problem is there, not due to the missing tokenization (could be wrong of cause).

If you still want to implement the tokenization of AArch64, this would be fine of cause. Note though that the `bf` tokenization is just an example (see the [docs](https://github.com/rizinorg/rizin/blob/dev/doc/asm_strings.md)). AArch64 will obviously have some more complex regex patterns for matching its tokens.

**Comment by XVilka** [comment]
Closed by https://github.com/rizinorg/rizin/commit/2fcf619598d1c8c5d868a597e30a1d6fe8bd08cd
