### ISSUE TITLE
IDA .sig files with version 5 compression not supported

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#417]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | -
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/012d3e96c2d586966e4d63e09102f3936506d27d

### Expected behavior

Open and dump the FLIRT file as usual.

### Actual behavior

Go to the `sig/` directory of the IDA Pro installation (any 7.x version would suffice):
```
$ rizin -
[0x00000000]> zfd ./pc/bcb5rt.sig
Sorry we do not support the signatures version 5 compression.
We encountered an error while parsing the file ./pc/bcb5rt.sig. Sorry.
```

It's implemented in:
- `librz/analysis/flirt.c` (function `flirt_parse()`)
- `librz/ore/cmd_zign.c`
- See also `doc/flirt.md`

**Comment by Autosaida** [comment]
I tried to use dumpsig.exe in the ida pro 7.5 sdk to process the different compressed versions of sig files in the sig folder, and they can all be dumped correctly. Does this mean that in order to fix this problem, the same function as the dumpsig.exe is required? So is the reverse analysis of the dumpsig.exe a practical means?

**Comment by Robot-RRR** [comment]
I tried to use dumpsig.exe in the ida pro 7.5 sdk to process the different compressed versions of sig files in the sig folder, and they can all be dumped correctly. Does this mean that in order to fix this problem, the same function as the dumpsig.exe is required? So is the reverse analysis of the dumpsig.exe a practical means?

**Comment by XVilka** [comment]
@Robot-RRR yes, the task implies data format reverse-engineering.

**Comment by XVilka** [comment]
@Robot-RRR check also these links too:
- https://github.com/williballenthin/lancelot/tree/master/flirt/src
- https://github.com/williballenthin/viv-utils/blob/master/viv_utils/flirt.py

**Comment by Autosaida** [comment]
After testing and analysis, I found that, in fact, sig files that compressed by version 6 cannot be dumped correctly. And the reason is as same as the version 5. Because the data will fail to decompress with the zlib in the flirt.c. (and the flirt.c does not restrict this). The relevant code in the flirt.c is as follows:
``` c
if (header->features & IDASIG__FEATURE__COMPRESSED) {
        if (version == 5) {
            eprintf("Sorry we do not support the signatures version 5 compression.\n");
            goto exit;
        }
        if (!(decompressed_buf = rz_inflate(buf, size, NULL, &decompressed_size))) {
            eprintf("Decompressing failed.\n");
            goto exit;
        }

        RZ_FREE(buf);
        buf = decompressed_buf;
        size = decompressed_size;
    }
```

Further analysis found that the compressed version 7 and higher have zlib file header `78 9C` after the sig file’s header and library name, but version 5 and version 6 do not.

Besides, I uncompressed the version 5(or 6) sig files with `zipsig.exe`, then compressed it with `zipsig.exe`. The data is just a little different from the original data. (`zipsig.exe` will increase the version to 10) So I think that the compression of version 5 (or 6) should be based on zlib. But it was a little different.

Therefore, the only way I can think of is to do reverse analysis on the `dumpsig.exe` or `zipsig.exe`, and observe how the decompression of v5 or v6 differs from the decompression of other versions to solve this task. (Because these two files could uncompress the v5 correctly) But it's a little difficult, is there a simpler and more feasible method?

(All the files I used are in ida pro 7.5 sdk)

**Comment by XVilka** [comment]
@Robot-RRR good research! Sadly, I am not aware of any other simpler ways. This format is undocumented and only RE and other implementations can help.

**Comment by Robot-RRR** [comment]
OK, I will reverse analyze the related files in combination with other related implementation in my spare time. And in the end, I will complete a related report. By the way, what is the specific deadline and how to submit the report?

**Comment by XVilka** [comment]
@Robot-RRR I wrote you an email - please check when you have time.

**Comment by b1llow** [comment]
I use python's zlib decompress the compressed_buf successful, use

```python
zlib.decompress(ori_, -zlib.MAX_WBITS)
```

but in c, I try

```c
	if (inflateInit2(&stream, -MAX_WBITS) != Z_OK) {
		return NULL;
	}
```

but failed.

**Comment by XVilka** [comment]
@imbillow negative wbits means the data without the header, but C version of zlib has the similar logic, not sure why.

**Comment by XVilka** [comment]
I recommend to check the exact reason of the error with API: https://www.zlib.net/manual.html

**Comment by b1llow** [comment]
It looks have the same logic.

[https://zlib.net/manual.html](https://zlib.net/manual.html)

```
ZEXTERN int ZEXPORT inflateInit2 OF((z_streamp strm,
                                     int  windowBits));
```
This is another version of inflateInit with an extra parameter. The fields next_in, avail_in, zalloc, zfree and opaque must be initialized before by the caller.
The windowBits parameter is the base two logarithm of the maximum window size (the size of the history buffer). It should be in the range 8..15 for this version of the library. The default value is 15 if inflateInit is used instead. windowBits must be greater than or equal to the windowBits value provided to deflateInit2() while compressing, or it must be equal to 15 if deflateInit2() was not used. If a compressed stream with a larger window size is given as input, inflate() will return with the error code Z_DATA_ERROR instead of trying to allocate a larger window.

windowBits can also be zero to request that inflate use the window size in the zlib header of the compressed stream.

**windowBits can also be –8..–15 for raw inflate. In this case, -windowBits determines the window size. inflate() will then process raw deflate data, not looking for a zlib or gzip header,** not generating a check value, and not looking for any check values for comparison at the end of the stream. This is for use with other formats that use the deflate compressed data format such as zip. Those formats provide their own check values. If a custom format is developed using the raw deflate format for compressed data, it is recommended that a check value such as an Adler-32 or a CRC-32 be applied to the uncompressed data as is done in the zlib, gzip, and zip formats. For most applications, the zlib format should be used as is. Note that comments above on the use in deflateInit2() applies to the magnitude of windowBits.

**Comment by b1llow** [comment]
And  `#define Z_DATA_ERROR   (-3)`, not an useful info.

**Comment by XVilka** [comment]
I recommend to check the Python sources to fish out the difference. I once used the same approach to find out the difference with the OCaml implementation of zlib algorithm. It might be also related to the used CRC function.

**Comment by b1llow** [comment]
Yeah, I am checking [https://github.com/python/cpython/blob/7d25254cf0763b62f4c4a3019e56385cab597b9f/Modules/zlibmodule.c#L415](https://github.com/python/cpython/blob/7d25254cf0763b62f4c4a3019e56385cab597b9f/Modules/zlibmodule.c#L415)
