### ISSUE TITLE
Add tag or commit hash to submodules 

### ISSUE THREAD

**Issue by bartoszek** [rizinorg/rizin#453]
Just stumble on a problem when packaging `rizin:0.1.0` for AUR.
`.gitmodules` doesn't name tag nor commit hash for submodules,
witch breaks compilation when submodule gets out of sync with 
release tag.

Could we please have tags or commit hashes for submodules for future tagged releases.

Building `rizin#tag=v0.1.0` throws missing file error in `meson.build`:
```
meson.build:486:0: ERROR: File shlr/sdb/src/dict.h does not exist.
```

[Quick fix I've applied to AUR/rizin](https://aur.archlinux.org/cgit/aur.git/commit/?h=rizin&id=3591d1f6f0aaeb6ab19313f5377b69d2be8db86e)

**Comment by ret2libc** [comment]
Hi and thanks for the report!

I think the problem here is that you are using `--remote` when doing the git-submodule-update (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rizin&id=8b046b6bf121cbc338a9273454523c6de9a2e3fe#n27). Because in theory git submodules already pin to a specific commit, as you can see from https://github.com/rizinorg/rizin/tree/v0.1.0/shlr, which shows a different commit for `sdb` than https://github.com/rizinorg/rizin/tree/dev/shlr).

Why are you using the `--remote` option? Could you try be removing it?

**Comment by bartoszek** [comment]
Yep, sorry for bothering, of course, you're right 😊 I've just [carry this flag from `-git` version of the package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rizin-git#n30) and didn't really consult the `man git submodule` if it intended behavior is what I assume it is... thought it is for assuring local submodule clone congruency with remote sha-1.
