### ISSUE TITLE
No commit sha comes from `rizin -v`

### ISSUE THREAD

**Issue by fangxlmr** [rizinorg/rizin#454]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | CentOS x86_64
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.1.0 0 @ linux-x86-64 git.0.1.0
commit: unknown build: 2021-01-25__18:52:29

### Expected behavior

Commit sha256 in `rizin -v`

### Actual behavior

No such a commit sha.

### Steps to reproduce the behavior

I build and install rizin as the doc said, and not sure why this happened. Any steps to find out why, and solve this?

**Comment by ret2libc** [comment]
Hi, thanks for the report. Nice catch, we missed that. The problem is in `meson.build` and likely because when you download the `rizin-src-v0.1.0.tar.xz` there is no git, so `gittip` does not get updated. I am not sure what is the best way to fix this, I would look around at what other meson projects do. Would you be willing to try to fix this?

**Comment by fangxlmr** [comment]
Honestly, I do have a .git directory, as the following says
```shell
➜  ~/Github/rizin git:(74ca7ff) git status 
# HEAD detached at 0.1.0
nothing to commit, working directory clean
➜  ~/Github/rizin git:(74ca7ff) git branch -a
* (detached from 0.1.0)
  dev
  remotes/origin/HEAD -> origin/dev
  remotes/origin/capstone-meson
  remotes/origin/debugoptimized-asan
  remotes/origin/dev
  remotes/origin/errno.h-rz_types.h
  remotes/origin/fix-tcc-configure
  remotes/origin/kill-acr
  remotes/origin/macos-sign-meson
  remotes/origin/newshell-expr-paren
  remotes/origin/newshell-fix-pipe-second-command
  remotes/origin/newshell-fix-pipe-second-command-windows-2
  remotes/origin/single-vs-double-quotes-windows
  remotes/origin/stable
  remotes/origin/stable-fix
  remotes/origin/subprocess-opt-api
  remotes/origin/swig
➜  ~/Github/rizin git:(74ca7ff) 
```

However, I just has no commit sha256 from `rizin -v`. (

**Comment by fangxlmr** [comment]
After removing the source code dir, running `git clone`, building and installing again, I still get the same result.
Trying to find out why... Not sure

**Comment by ret2libc** [comment]
> After removing the source code dir, running `git clone`, building and installing again, I still get the same result.
> Trying to find out why... Not sure

I was able to reproduce on CentOS 7.

**Comment by ret2libc** [comment]
The problem is in these lines https://github.com/rizinorg/rizin/blob/dev/meson.build#L58 .
All of them use `-C` which is not recognized by the git version shipped with CentOS 7. Do you want to try and submit a patch? Otherwise I can do it, no problem. Your choice.

**Comment by ret2libc** [comment]
There are two problems:
1) no commit when building Rizin from the release tarball. This should be easy to fix, we just need to use `gittip = ''` instead of `gittip = 'unknown'`, because https://github.com/rizinorg/rizin/blob/dev/librz/util/str.c#L3818 checks if the string is empty because printing it. When the build comes from the release, we don't need the specific commit because it's already known from the version
2) systems that do not support `-C` git option. This case is a bit trickier.. One solution could be to wrap those `git` commands in a separate python script, stored in `./sys/`, that tries to execute the command with `-C` or, if that fails, execute `cd <repo> ; <git-command> ; cd ..`.

**Comment by fangxlmr** [comment]
> The problem is in these lines https://github.com/rizinorg/rizin/blob/dev/meson.build#L58 .
> All of them use `-C` which is not recognized by the git version shipped with CentOS 7. Do you want to try and submit a patch? Otherwise I can do it, no problem. Your choice.

I guess you might be better for this.

**Comment by ret2libc** [comment]
@fangxlmr Hi, could you check if the PR https://github.com/rizinorg/rizin/pull/465 works for you?

**Comment by fangxlmr** [comment]
```shell
$ rizin -v
rizin 0.2.0-git @ linux-x86-64
commit: 4071f0b145c40d62234f17c366f955b015d54da3, build: 2021-01-27__15:39:34
```
@ret2libc Yes, it does work! Nice job!
