### ISSUE TITLE
Symlink rizin to rz - Package releases

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#550]
**Is your feature request related to a problem? Please describe.**
The current release package binaries don't provide a symlink for `rizin` => `rz`, which is a bit inconsistent considering that all the other tools contained in the packages start with `rz-`.

**Describe the solution you'd like**
Symlink for `rizin` => `rz` is contained in the package releases.

**Describe alternatives you've considered**
💔 

**Additional context**
radare2 releases have symlinks for `radare2` => `r2` 🔗

**Comment by caribpa** [comment]
Jokes aside, an alternative is to just provide `rz` instead of `rizin`.

**Comment by ret2libc** [comment]
We did not do that on purpose, because `rz` is too short, too common and already provided by multiple distributions. `rizin` is not such a long name so we prefer to stay with full name `rizin`.

`rz` remains the prefix for everything rizin related, but we do not have just "rz", sorry.

Not sure we really want to change all `rz-*` to `rizin-*`... @thestr4ng3r @XVilka @ITAYC0HEN @wargio @kazarmy .

**Comment by thestr4ng3r** [comment]
> Not sure we really want to change all `rz-*` to `rizin-*`... @thestr4ng3r @XVilka @ITAYC0HEN @wargio @kazarmy .

Definitely not. `rz` is the common abbreviation for rizin, including its API, but that doesn't necessarily imply that the main executable must also be able to be called by `rz`.

Though in fact, we did consider having an `rz` symlink, but it turned out that many distributions already ship an executable called `rz` so enforcing that wouldn't work.

**Comment by ret2libc** [comment]
I'm closing this for now as this was already considered multiple times and we chose against the symlink. This does not mean, though, that specific distributions cannot provide such link if they are able, somehow. We just cannot provide directly from us, to avoid problems with the user system.

**Comment by caribpa** [comment]
I see, thank you for explaining the issue.

**Comment by caribpa** [comment]
Just a last thought, have you consider changing the command line name for the sake of consistency?

`rzn` or `riz` don't seem to be used by any official package in Arch Linux (can't say about other distros), and a quick search on the internet also don't find anything. This could also lead to remove the hyphen from the other tools so that they can be pronounced 🙂 , examples:
- `rizagent`
- `rizrun`
- `rizegg` (instead of `rizgg`, after all it is used for [eggs](https://github.com/rizinorg/rizin/blob/dev/librz/egg/README))
...

**Comment by ITAYC0HEN** [comment]
Thanks for these wise suggestions @caribpa! Indeed, you had similar ideas like we had we started - that's very nice :)
We did consider some alternatives and decided that `rz-*` prefix fits the best. Pronunciation wise it is not complex. rz-bin is 'Ar Zi Bin', and so on.

**Comment by caribpa** [comment]
@ITAYC0HEN Thanks for clarifying!

I love the `rz` abbreviation, it is just that my OCD got triggered when I installed Rizin on Windows and the symlink `rizin` => `rz` wasn't there. Then, I realized the inconsistency with the naming as other tools start with `rz-` whereas the 'main' tool is `rizin` instead of `rz` 😮

But don't worry, I'll get over this drama with the naming at some point 😃

Sorry for keep dragging this non-issue 🙏

**Comment by kazarmy** [comment]
I think it's possible to have the symlink `rz` => `rizin` on Windows for convenience's sake, because binaries there usually are not installed at a central location. There will be an inconsistency with Linux which is probably not good for muscle memory, but that will be moot if you exclusively work with Rizin on Windows.
