### ISSUE TITLE
Remote cmd mode - Unable to pass a descriptor

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#552]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64 commit: 3e64a2e16a4a4d4bc7879299152e67c99084a685, build: 2021-02-09__17:04:35

### Expected behavior
Passing a descriptor to the remote cmd mode (`=!=`) starts the remote cmd mode on the given descriptor.

### Actual behavior

![remote-cmd](https://user-images.githubusercontent.com/14806975/107392269-ca65c400-6af9-11eb-96d0-7e536d67ac80.png)

#### Server
- `cd /bin`
- `rz rap://:8080`

#### Client
- `rz --`
- `+= rap://localhost:8080/rizin`
- `=!= 0`
- 💔 

This issue is not present in radare2, it correctly starts a remote cmd mode with `=!=0`.

Currently there's no way to start a remote cmd mode in Rizin, only starting the client with `rz rap://localhost:8080/rizin` works, but this can't be done with TCP/UDP and probably others.

**Comment by ret2libc** [comment]
Thanks for this, I will have a look!

Honestly, all the "remote" part needs to be re-thinked a bit because it's quite separated from the rest right now and commands end up being executed through a completely different code path... However, I'm going to fix this and then at some point we will go back to see how to improve the whole situation.

For this specific bug:
- [ ] need to add optional arguments to `=!=` in cmd_descs.yaml
- [ ] make sure code under `if (core->cmdremote)` in `cmd.c:rz_core_cmd` is executed when in newshell.
