### ISSUE TITLE
Replace librz/crypto with an external library

### ISSUE THREAD

**Issue by ghost** [rizinorg/rizin#632]
**Is your feature request related to a problem? Please describe.**
Right now Rizin is implementing various crypto function. But it is bugged and not really reliable.

**Describe the solution you'd like**
Use an external library:
* libsodium
* virgil-crypto-c
* crypto++
* libtomcrypt 
* gnupg
* ect

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by ret2libc** [comment]
Can you show in which way it is buggy? Also, going from memory i think you can already compile with openssl lib which should replace some parts iirc

**Comment by ghost** [comment]
See line 34 librz/crypto/p/crypto_aes_algo.c
Various files are using bad practices such as global variable.

The majority of those file are from external libraries (or code snippet).

**Comment by ghost** [comment]
> Also, going from memory i think you can already compile with openssl lib which should replace some parts iirc

Okay, but if we can use openssl to replace various functions, we could remove those functions. In theory, is it possible to static link openssl?

**Comment by XVilka** [comment]
1. Not all of RzCrypto is available in OpenSSL
2. Not all of your listed alternatives are really suitable for our needs
3. Some of the functions can be really dropped though if it's possible to use an external library
4. Keeping RzCrypto as a module is important if someone will want to implement custom crypto algorithm which is sometimes handy in reversing some firmware or malware.
5. Most crypto libraries often drop outdated/broken crypto algorithms in newer version due to the security reasons. Rizin is a reverse engineering tool, thus it should be able to handle MD4 algorithm, e.g., even after it was removed from OpenSSL.

**Comment by XVilka** [comment]
I think after refactoring done by @wargio we can safely close this issue:
- https://github.com/rizinorg/rizin/pull/1072
- https://github.com/rizinorg/rizin/commit/54fd6a66bcdf397fa438bc9e48aaac10aa01f8a3
