### ISSUE TITLE
Add an API for the C syntax output

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#727]
Currently, a lot of commands, especially `t` commands often output some data in the C syntax format.
It might be useful for some of the `pf` and `i` commands as well.

I propose the API similar to the PJ to form such output in a consistent and succinct way.

We also might want to add a new kind of output mode - `RZ_OUTPUT_MODE_C`.

**Comment by ret2libc** [comment]
One thing to consider when adding new "modes" is that every mode is a new suffix latter that, in some way, we reserve for a special purpose. That means that if we reserve, for example, the `c` suffix for the "output C mode", users would expect that another command e.g. `zc` would have in some way a similar meaning... Just something to consider :)

**Comment by ret2libc** [comment]
Also, I think that as there are possibly more output formats that require some form of states (e.g. JSON has PJ, SDB output has SDB, etc.) we should group these states in a single structure e.g. `RzOutputState` or something like that, because otherwise passing around pointers to all these different types of variables is going to be a mess IMO.

**Comment by ITAYC0HEN** [comment]
I claim that people.who use special output formats (json, yaml, c) use it for scripting or exporting data. And as such, the value of single letter suffix to represent a type isn't a big deal for them in compare with people who run the shell commands.

Meaning that replacing j, c, t suffix with something longer but more self explanatory, wouldn't be a big of an issue because it wasn't built for a routine repetitive usage from the shell. 

Hence `pd:json`, `afl:yaml`, or `pd | format json` and similar are something we can consider.

**Comment by ret2libc** [comment]
I love `pd:json` and `afl:yaml` actually!!

**Comment by XVilka** [comment]
@DMaroo see also this discussion, by the way.

**Comment by ret2libc** [comment]
I'm honestly not sure if it's worth adding a new output mode for C. So far I'd prefer special commands like we have in `t`.

**Comment by DMaroo** [comment]
In my knowledge, for types it won't be a problem since the pretty print API will output in valid C (valid indentation and everything). So adding this mode would not require rewriting any of the printing functions.

**Comment by XVilka** [comment]
Fixed by @DMaroo
