### ISSUE TITLE
Convert `C` (cmd_meta.c) commands to rzshell

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#792]

**Comment by ret2libc** [comment]
Few issues to consider while doing this conversion:
1) some `C` commands change behaviour based on the fact that there is `@` or not. This is IMHO wrong, because a command should behave the same no matter if there is `@` or not. In particular, the problem was about `C @ <addr>` (set a new meta) vs `C` (list meta). I don't remember if I already did something about this, but worth double checking
2) `C` commands usually have the same sub-commands (e.g. `Cs`, `Cd`, `Cv`, etc.). We should check if they really share the same "interface" or not and whether we can duplicate all the handlers or if we should find a way to avoid duplicated stuff in the command yaml description.

Actually... Are you sure we can do everything for 0.2.0? I could envision it can take some time and discussion to get `C` right.

**Comment by ret2libc** [comment]
See https://github.com/rizinorg/rizin/issues/802 as well.
