### ISSUE TITLE
The testsuite if broken on some architectures

### ISSUE THREAD

**Issue by jvoisin** [rizinorg/rizin#837]
It seems that the testsuite [doesn't play well]( https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/rizin/APKBUILD#L8-12 ) on Alpine Linux: x86, armv7, armhf, s390x and mips64 are currently broken there.

**Comment by ret2libc** [comment]
Is the build done without internet? I think there are some tests that require to download the PDB file from a remote server. Also, likely the debug tests will fail.

**Comment by jvoisin** [comment]
I think that the builder has access to internet.

**Comment by ret2libc** [comment]
I suggest you paste here the exact problem that happens on Alpine, otherwise it's a bit hard to even understand what's going on...

**Comment by XVilka** [comment]
@jvoisin @ret2libc looks exactly the same as https://github.com/rizinorg/rizin/issues/279
Also serialize_analysis test was fixed since, only PDB one left. Note, since we have the Travis CI with S390 and PPC platforms, it's easy to send a pull request ;)

*P.S. See also https://github.com/rizinorg/rizin/issues/297 *

**Comment by ret2libc** [comment]
Shall we close this then?
