### ISSUE TITLE
Explain RZ_OWN, RZ_BORROW, etc in developers documentation

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#863]
There are some conventions that are used in Rizin code but unexplained in DEVELOPERS.md.
They are:
- `RZ_OWN`
- `RZ_BORROW`
- `RZ_NULLABLE`
- `RZ_NONNULL`
- `RZ_INOUT`
- `RZ_OUT`
- `RZ_DEPRECATE`

They are defined in `librz/include/rz_types.h` and briefly explained there, but it's not enough for new developers.

**Comment by chinggg** [comment]
Hi, I am a newcomer. It seems that the DEVELOPERS.md contains mainly guidelines like codestyles that are worth attention. Can you suggest the place to hold these explanations of `RZ_*` definitions and the content of explanations ?

**Comment by ret2libc** [comment]
https://github.com/rizinorg/rizin/blob/ddcefec61417ae908f4d7c90893f0d35ad109414/librz/include/rz_types.h#L45

**Comment by XVilka** [comment]
@chinggg I think a new section in DEVELOPERS.md would be nice, something like "Manage ownership" or something, like "Manage endianess" currently.

**Comment by chinggg** [comment]
@ret2libc Thanks! I know they are defined there, but I cannot simply copy these comments to DEVELOPERS.md
> They are defined in librz/include/rz_types.h and briefly explained there, but it's not enough for new developers.

@XVilka Thanks for giving suggestion for place to hold explanations.
I will try to explain these conventions even though I do not understand them well myself.

**Comment by ret2libc** [comment]
@chinggg I suggest you look for uses of some of those defines, they should make it clearer how to use them and what they are for.
Some should be simple, like RZ_NONNULL near an argument of a function means that the argument should not be NULL. RZ_OUT near an argument means that the parameter provides some results (e.g. through a pointer), etc. etc.

I guess the trickier are RZ_BORROW and RZ_OWN. If you need some help understanding others don't hesitate to ask!

**Comment by chinggg** [comment]
@XVilka @ret2libc I searched for "pointer ownership" and there are good answers in [Stack OverFlow](https://stackoverflow.com/questions/60046802/understanding-memory-ownership-models-in-c). 
Now I have written a draft, you can check it and give suggestions. Since I am not a native english speaker, there may be mistakes. Feel free to point them out!

**Comment by chinggg** [comment]
# Manage Ownership
The C standard does not provide any model of memory ownership, so Rizin uses macros to indicate pointer ownership, which are defined in `librz/include/rz_types.h`:

```c
#define RZ_IN        /* do not use, implicit */
#define RZ_OUT       /* parameter is written, not read */
#define RZ_INOUT     /* parameter is read and written */
#define RZ_OWN       /* pointer ownership is transferred */
#define RZ_BORROW    /* pointer ownership is not transferred, it must not be freed by the receiver */
#define RZ_NONNULL   /* pointer can not be null */
#define RZ_NULLABLE  /* pointer can be null */
#define RZ_DEPRECATE /* should not be used in new code and should/will be removed in the future */
```

Most of them are easy to understand and you can see brief explanation in the comments. But `RZ_OWN` and `RZ_BORROW` may be a little tricky to new developers.

Here is a short example of how we usually use `RZ_BORROW`:

```c
RZ_API void rz_analysis_var_add_constraint(RzAnalysisVar *var, RZ_BORROW RzAnalysisVarConstraint *constraint) {
	rz_vector_push(&var->constraints, constraint);
}
```

In this example, we use `RZ_BORROW` to indicate that the pointer `constraint` is "borrowed" and its "ownership" is not transfered. Here "ownership" means who is responsible for freeing the memory that was allocated. When memory is dynamically allocated with `malloc`, we should ensure that the address of that memory is passed to `free` exactly one time.

To take a deep dive into pointer ownership model, see https://resources.sei.cmu.edu/asset_files/WhitePaper/2013_019_001_55008.pdf

**Comment by ret2libc** [comment]
> # Manage Ownership
> The C standard does not provide any model of memory ownership, so Rizin uses macros to indicate pointer ownership, which are defined in `librz/include/rz_types.h`:

I would be a bit more generic. These are not just about ownership, but also to "explain"/"describe" how arguments of a functions are used. Whether they are used as input, input/output/just output, how the ownership is handled but also whether you can use null or not... I'm not sure exactly how to put it, but it is not just ownership.

> Most of them are easy to understand and you can see brief explanation in the comments. But `RZ_OWN` and `RZ_BORROW` may be a little tricky to new developers.
> 
> Here is a short example of how we usually use `RZ_BORROW`:
> 
> ```c
> RZ_API void rz_analysis_var_add_constraint(RzAnalysisVar *var, RZ_BORROW RzAnalysisVarConstraint *constraint) {
> 	rz_vector_push(&var->constraints, constraint);
> }
> ```
> 
> In this example, we use `RZ_BORROW` to indicate that the pointer `constraint` is "borrowed" and its "ownership" is not transfered. Here "ownership" means who is responsible for freeing the memory that was allocated. When memory is dynamically allocated with `malloc`, we should ensure that the address of that memory is passed to `free` exactly one time.

I like this part and I agree it is probably the only real one that deserves some example. Maybe I'd even make a more complete example, showing the difference between RZ_BORROW and RZ_OWN and how the caller should behave differently in the two cases.

> 
> To take a deep dive into pointer ownership model, see https://resources.sei.cmu.edu/asset_files/WhitePaper/2013_019_001_55008.pdf

I'd remove this.

**Comment by chinggg** [comment]
@ret2libc Thanks! I think your suggestion is useful.
> I like this part and I agree it is probably the only real one that deserves some example. Maybe I'd even make a more complete example, showing the difference between RZ_BORROW and RZ_OWN and how the caller should behave differently in the two cases.

I already use `grep` to find where `RZ_OWN` and `RZ_BORROW` are used. I must admit that most of them are more obscure than the example I posted above so I cannot understand them well myself, let alone explain them clearly.

To be specific, there are 2*2=4 places that `RZ_OWN` and `RZ_BORROW` could be found in my observation.
(1) before the **return type** of **function declaration**.
```c
RZ_API RZ_OWN char *rz_type_func_args_type(Sdb *TDB, RZ_NONNULL const char *func_name, int i);
```
in `librz/include/rz_util/rz_ctypes.h`.

(2) before the **parameter** in **function declaration**
``` 
RZ_API RzCoreSymCacheElement *rz_coresym_cache_element_new(RzBinFile *bf, RzBuffer *buf, ut64 off, int bits, RZ_OWN char *file_name);
```
in `librz/bin/format/mach0/coresymbolication.h`.

(3) before the **return type** of **function definition**
```c
 RZ_API RZ_OWN char *rz_type_func_args_type(Sdb *TDB, RZ_NONNULL const char *func_name, int i) {
	const char *query = sdb_fmt("func.%s.arg.%d", func_name, i);
	char *ret = sdb_get(TDB, query, 0);
	if (ret) {
		char *comma = strchr(ret, ',');
		if (comma) {
			*comma = 0;
			return ret;
		}
		free(ret);
	}
	return NULL;
}
```
in `librz/util/utype.c`. And it matches the function declaration in (1).

(4) before the **parameter** in **function definition**
```c
RZ_API void rz_analysis_var_add_constraint(RzAnalysisVar *var, RZ_BORROW RzAnalysisVarConstraint *constraint) {
	rz_vector_push(&var->constraints, constraint);
}
```
in `librz/analysis/var.c`, which is the shortest function I found, so I used it as the example.

I am confused about the four different kinds of usage. And I have some questions that new developers may wonder too.

What does `ownership` means when `RZ_OWN`/`RZ_BORROW` is before the return type of function? 

Does `RZ_OWN` must be found the same time in one function's declaration and definition?

What restrictions are actually wanted by using `RZ_OWN` and `RZ_BORROW`? 

How do I know when to use them? 

How can I check whether I have used them correctly by reviewing my code, since there may be no tools?

**Comment by ret2libc** [comment]
I'd say there are only 2 cases, as it doesn't really matter whether you use them in definition/declaration. I think you should use them in both, though there is no check in place to ensure that you use them consistently in both.

> (1) before the return type of function declaration.

* `RZ_OWN`: the ownership of the returned object is transferred to the caller. The caller *owns* the object, so it must free it (or ensure that something else frees it).
* `RZ_BORROW`: the ownership of the returned object is not transferred. The caller can use the object, but it does not own it, so it should not free it.

> (2) before the parameter in function declaration

* `RZ_OWN`: the ownership of the passed argument is transferred to the callee. The callee now owns the object and it is its duty to free it (or ensure that something else frees it). In any case, the caller should not care anymore about freeing that passed object.
* `RZ_BORROW`: the ownership of the passed argument is *not* transferred to the callee, which can use it but it should not free it. After calling this function, the caller still owns the passed object and it should ensure that at some point it is freed.


Examples:
```C
RZ_OWN MyString *capitalize_str(RZ_BORROW char *s) {
  MyString *m = RZ_NEWS(MyString);
  m->s = strdup(s);
  capitalize(m->s);
  return m;
}

int main() {
  char *s = strdup("Hello World");
  MyString *m = capitalize_str(s);
  // s was RZ_BORROW, so main still need to free it
  free(s);
  // ... use m ....
  // m was RZ_OWN, so main now has to free it
  my_string_free(m);
}
```

```C
RZ_BORROW MyString *capitalize_str(RZ_BORROW MyFile *f, RZ_OWN char *s) {
  MyString *m = RZ_NEWS(MyString);
  m->s = s;
  capitalize(m->s);
  f->m = m;
  return m;
}

int main() {
  char *s = strdup("Hello World");
  MyFile *f = create_my_file();
  MyString *m = capitalize_str(f, s);
  // s was RZ_OWN, so main does not need to free it. s is now owned by `m`
  // ... use m ....
  // m was RZ_BORROW, so main is just borrowing it from `f`, and it does not have to free it.
  my_file_free(f);
  // f was created by main and never transferred to anything else, so main needs to free it.
}
```

To answer your questions:

> Does RZ_OWN must be found the same time in one function's declaration and definition?

Ideally yes.

> What restrictions are actually wanted by using RZ_OWN and RZ_BORROW?

Right now there is no special compiler-time restrictions, but those things are rather used as an indication to developers, so that they don't have to read maybe a complicated functions to know whether they should still free objects or not. Sometimes it may not be immediately clear whether the object you are getting from a function shall be freed or not, etc.

> How do I know when to use them?

I'd say that we should use them whenever it makes sense :D For example, it is common that if your function return `const char *`, the caller should not free it (because of the const). So specifying RZ_BORROW in this case is probably redundant. If you have a function called `RzBinSymbol *rz_bin_symbol_new` is quite clear that the returned object is owned by the caller. If, however, you think you have a behaviour that goes against the usual understanding, it's probably worth using these specifiers. 

> How can I check whether I have used them correctly by reviewing my code, since there may be no tools?

Good question, without good answer. There is no good way to check if you have used them correctly :(

**Comment by chinggg** [comment]
@ret2libc Thanks for your detailed explanation! The final exams of winter semester are waiting for me in the next two days. I will rewrite my section and make a PR after that.
